language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - "7.4snapshot"

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --prefer-stable --no-interaction --no-progress --optimize-autoloader"
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.4snapshot'

install:
  - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $PREFER_LOWEST

before_script:
  - php --version
  - composer --version

script:
  - ./vendor/bin/phpunit ./tests/
